[project]
name = "a2a-holiday-planner"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "a2a",
  "uvicorn",
  "httpx",
  "python-dotenv",
  "starlette",
  "langgraph",
  "langchain-core",
  "langchain-openai",
  "crewai",
  "crewai-tools",
  "pydantic",
  "streamlit",
  "rich",
]
